### ISSUE TITLE
Duplicate symbol error when compiling with Clang 13.0 on macOS

### ISSUE THREAD

**Issue by stfnp** [newlawrence/Calculate#95]
I wanted to use this library in my project, but I'm getting a linker error about duplicate symbols when including it in more than one translation unit. In my example I have two .cpp files `DoubleSpinBox.cpp` and `IntegerSpinBox.cpp` that both include the `calculate.hpp` header. This results in the following error:

    duplicate symbol 'calculate::defaults::complex<false>' in:
        CMakeFiles/virtualbow-gui.dir/source/gui/widgets/DoubleSpinBox.cpp.o
        CMakeFiles/virtualbow-gui.dir/source/gui/widgets/IntegerSpinBox.cpp.o
    duplicate symbol 'calculate::defaults::real<false>' in:
        CMakeFiles/virtualbow-gui.dir/source/gui/widgets/DoubleSpinBox.cpp.o
        CMakeFiles/virtualbow-gui.dir/source/gui/widgets/IntegerSpinBox.cpp.o

The "offending" code seems to be this section in `lexer.hpp`:

https://github.com/newlawrence/Calculate/blob/673e4c735779727f7846e8ee3a532d2d81df9dc6/include/calculate/lexer.hpp#L33-L51

The error only happens with the Clang compiler though, GCC on Linux and Windows seems to have no problem. So maybe Clang is more strict about something or it might even be a compiler bug. I tried making those constants `static`. The result is that it compiles successfully with Clang, but not with GCC anymore... Any idea what the proper solution would be here?

**Comment by newlawrence** [comment]
Hi! First of all, I want to thank your trust and will to use my software.

Unfortunately I'm not actively maintaining this project at the moment, but I took the time to give a quick try and see if I could come up with a quick solution to your issue.

You're right, I've tried to include the library in two different translation units and **Clang** (in its version **13**) complains about duplicated symbols. In my opinion **Clang** is right here, strictly speaking those symbols are duplicated. Long story short, **C++17**'s inline variables would have come in handy in order to have some unique strings defined in headers as these ones but, as I didn't have the feature available at that time (the library targets **C++14**), I chose to just make them `constexpr` hoping for them to be inlined within the code. Well, it turns out that those specific strings are not being inlined with **Clang** and thus their symbols leak to the binary objects.

A quick solution for you is to declare all the strings as `inline` (see the [attatched patch](https://github.com/newlawrence/Calculate/files/8934425/inline_strings.patch.zip)) in the case upgrading to **C++17** is an option for you. If you're stuck with **C++14**, we can think about another (more elaborate) solutions like [this one](https://stackoverflow.com/a/38043566)...

**Comment by stfnp** [comment]
Thank you for the quick response! C++17 is okay for me, so the `inline` solution worked perfectly.
